@startuml

I1_Lugar *-- CatedralDeSantiago : Se Encuentra en:

Ec1 *-- CatedralDeSantiago : Se Construyó Durante:

Ec2 *-- CatedralDeSantiago : Se Construyó Durante:

Class CatedralDeSantiago{
Nombre = “Catedral de Santiago de Compostela”
Culto = Católico
Fecha primera consagración = 1128
Fecha seg unda consagración = 3 de abril de 121 1
Fecha declaración BIC = 1896
Material = Granito
Esti lo = Románico, Gótico, Barroco, Plateresco, Neoclásico
}

Class Ec1{
Fecha inicio = 1075
Fecha fin = 1122
}
Class Ec2{
Fecha inicio = 1168
Fecha fin = nulo
}

Class I1_Lugar{
Ciudad = “Santiago de Compostela”
Comunidad = “Galicia”
País = “España”
}
@enduml